// <auto-generated />
using System;
using Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119053011_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Specialization")
                        .HasColumnType("int");

                    b.Property<int?>("WorkExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateOnly(1984, 1, 20),
                            Name = "Timofeev Oleg Borisovich",
                            Passport = "1223 456782",
                            Specialization = 0,
                            WorkExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateOnly(1989, 7, 15),
                            Name = "Ivanova Anna Sergeevna",
                            Passport = "1234 567893",
                            Specialization = 2,
                            WorkExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateOnly(1979, 3, 8),
                            Name = "Petrov Dmitry Viktorovich",
                            Passport = "1345 678904",
                            Specialization = 1,
                            WorkExperience = 15
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateOnly(1986, 11, 25),
                            Name = "Sidorova Elena Mikhailovna",
                            Passport = "1456 789015",
                            Specialization = 4,
                            WorkExperience = 12
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateOnly(1982, 5, 30),
                            Name = "Kozlov Artem Igorevich",
                            Passport = "1567 890126",
                            Specialization = 3,
                            WorkExperience = 14
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateOnly(1976, 8, 12),
                            Name = "Fedorov Sergey Vasilyevich",
                            Passport = "1678 901237",
                            Specialization = 5,
                            WorkExperience = 9
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateOnly(1957, 2, 28),
                            Name = "Fedorov Ivan Vasilyevich",
                            Passport = "2465 436678",
                            Specialization = 5,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateOnly(1994, 10, 5),
                            Name = "Fedorov Oleg Vasilyevich",
                            Passport = "9999 999999",
                            Specialization = 5,
                            WorkExperience = 1
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateOnly(1995, 12, 15),
                            Name = "Fedorov Petr Vasilyevich",
                            Passport = "6666 666666",
                            Specialization = 5,
                            WorkExperience = 4
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateOnly(1996, 4, 3),
                            Name = "Fedorov Kirill Vasilyevich",
                            Passport = "7777 777771",
                            Specialization = 5,
                            WorkExperience = 2
                        });
                });

            modelBuilder.Entity("Domain.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<int?>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("RhFactor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Moscow, Sadovaya st., 147, apt. 1",
                            Birthday = new DateOnly(1989, 5, 15),
                            BloodGroup = 0,
                            Gender = 0,
                            Name = "Ivanov Petr Sidorovich",
                            Passport = "2003 256748",
                            Phone = "+79371234567",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "St. Petersburg, Lenina st., 25, apt. 45",
                            Birthday = new DateOnly(1992, 8, 22),
                            BloodGroup = 1,
                            Gender = 1,
                            Name = "Petrova Maria Ivanovna",
                            Passport = "2015 123456",
                            Phone = "+79161234567",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Novosibirsk, Tsentralnaya st., 10, apt. 12",
                            Birthday = new DateOnly(1982, 3, 10),
                            BloodGroup = 2,
                            Gender = 0,
                            Name = "Sidorov Andrey Vladimirovich",
                            Passport = "1998 654321",
                            Phone = "+79031234567",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Yekaterinburg, Pushkina st., 33, apt. 78",
                            Birthday = new DateOnly(1993, 11, 30),
                            BloodGroup = 3,
                            Gender = 1,
                            Name = "Kuznetsova Elena Sergeevna",
                            Passport = "2010 987654",
                            Phone = "+79261234567",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kazan, Gagarina st., 15, apt. 23",
                            Birthday = new DateOnly(1999, 7, 5),
                            BloodGroup = 0,
                            Gender = 0,
                            Name = "Smirnov Alexey Petrovich",
                            Passport = "2005 456789",
                            Phone = "+79501234567",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nizhny Novgorod, Sovetskaya st., 47, apt. 56",
                            Birthday = new DateOnly(2005, 2, 14),
                            BloodGroup = 1,
                            Gender = 1,
                            Name = "Vasilyeva Olga Dmitrievna",
                            Passport = "2018 321654",
                            Phone = "+79991234567",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "Moscow, Tsentralnaya st., 10",
                            Birthday = new DateOnly(1974, 12, 5),
                            BloodGroup = 1,
                            Gender = 0,
                            Name = "Nikolaev Viktor Ivanovich",
                            Passport = "1975 111111",
                            Phone = "+79111111111",
                            RhFactor = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "St. Petersburg, Nevsky pr., 25",
                            Birthday = new DateOnly(1981, 9, 18),
                            BloodGroup = 2,
                            Gender = 1,
                            Name = "Orlova Svetlana Petrovna",
                            Passport = "1980 222222",
                            Phone = "+79222222222",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "St. Petersburg, Nevsky pr., 40",
                            Birthday = new DateOnly(2004, 4, 25),
                            BloodGroup = 1,
                            Gender = 0,
                            Name = "Olegov Svetoslav Petrovich",
                            Passport = "1742 123575",
                            Phone = "+79133546362",
                            RhFactor = 1
                        },
                        new
                        {
                            Id = 10,
                            Address = "St. Petersburg, Nevsky pr., 120",
                            Birthday = new DateOnly(2004, 6, 12),
                            BloodGroup = 0,
                            Gender = 1,
                            Name = "Revenkova Olga Igorevna",
                            Passport = "1980 222223",
                            Phone = "+79123456123",
                            RhFactor = 1
                        });
                });

            modelBuilder.Entity("Domain.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAgain")
                        .HasColumnType("bit");

                    b.Property<string>("NumberOfCabinet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfVisit = new DateTime(2024, 1, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsAgain = false,
                            NumberOfCabinet = "101-A",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfVisit = new DateTime(2024, 1, 17, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsAgain = true,
                            NumberOfCabinet = "205-B",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateOfVisit = new DateTime(2024, 1, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsAgain = false,
                            NumberOfCabinet = "315-C",
                            PatientId = 5
                        },
                        new
                        {
                            Id = 4,
                            DateOfVisit = new DateTime(2024, 1, 22, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsAgain = false,
                            NumberOfCabinet = "112-D",
                            PatientId = 6
                        },
                        new
                        {
                            Id = 5,
                            DateOfVisit = new DateTime(2024, 1, 13, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsAgain = true,
                            NumberOfCabinet = "308-E",
                            PatientId = 3
                        },
                        new
                        {
                            Id = 6,
                            DateOfVisit = new DateTime(2024, 1, 21, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsAgain = false,
                            NumberOfCabinet = "101-A",
                            PatientId = 4
                        },
                        new
                        {
                            Id = 7,
                            DateOfVisit = new DateTime(2024, 1, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsAgain = false,
                            NumberOfCabinet = "101-A",
                            PatientId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateOfVisit = new DateTime(2024, 1, 12, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            IsAgain = true,
                            NumberOfCabinet = "205-B",
                            PatientId = 7
                        },
                        new
                        {
                            Id = 9,
                            DateOfVisit = new DateTime(2024, 1, 5, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            IsAgain = false,
                            NumberOfCabinet = "315-C",
                            PatientId = 8
                        },
                        new
                        {
                            Id = 10,
                            DateOfVisit = new DateTime(2024, 1, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 5,
                            IsAgain = true,
                            NumberOfCabinet = "308-E",
                            PatientId = 8
                        },
                        new
                        {
                            Id = 11,
                            DateOfVisit = new DateTime(2023, 12, 30, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            IsAgain = true,
                            NumberOfCabinet = "101-A",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 12,
                            DateOfVisit = new DateTime(2024, 1, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsAgain = false,
                            NumberOfCabinet = "112-D",
                            PatientId = 2
                        },
                        new
                        {
                            Id = 13,
                            DateOfVisit = new DateTime(2024, 1, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            IsAgain = false,
                            NumberOfCabinet = "111-D",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 14,
                            DateOfVisit = new DateTime(2024, 1, 18, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 7,
                            IsAgain = false,
                            NumberOfCabinet = "121-C",
                            PatientId = 3
                        });
                });

            modelBuilder.Entity("Domain.Visit", b =>
                {
                    b.HasOne("Domain.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
